* Awesomeness with W3M

** Preface
Terminal web browsers are a joke, no doubt about it, but W3M is something extra...
You should watch Gotbletu's youtube videos on W3M. He's done some cool things with it.
w3m.png

** Features
W3M can execute [1]CGI scripts and display the output of the script to the screen.
The only reference to using cgi scripts was on [2]this w3m manual page.
I don't entirley understand how it works, but I guess printing out http header information to the screen can be used to control w3m.
I'll show you some cool scripts you could use later in this page.

*** Here are some notable features of w3m:
1. Fully customizable keybindings
2. User scripts (diy addons)
3. Images (install w3m-img)
4. Tabbing
5. Cookie management, history, useragent, autofill, etc.

Image previews only work well on a select number of terminals. Xterm and Urxvt work well. Other terminals may either not display them at all or have a lot of flickering.

* Basic configuration
Here's a list of important files:

1. ~/.w3m/config - Contains browser config options
2. ~/.w3m/config/keymap - Keybindings. "keymap KEY NULL" clears the keys original mapping.
3. ~/.w3m/mailcap - Dictates which programs open which filetypes

The config file is generated by w3m automatically.
You can either edit this config directly or inside w3m itself.
One interesting variable is "extbrowser".
You can specify an external command to run on a webpage url.
The external browser can be invoked using: <NUM>M

#+begin_src shell
# Example options (~/.w3m/config)
extbrowser sh -c 'printf %s "$0" | xsel -b && notify-send "W3M" "URL COPIED"'
extbrowser2 mpv  %s
extbrowser3 youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4" %s
extbrowser4 setsid xdg-open %s &
#+end_src

The keymap file is created manually. I won't go too much into detail.
Here's an overly populated example config. [2]
Besides basic w3m movement, you could also make cool keybindings like these:

#+begin_src shell
# Toggle images
keymap i COMMAND "SET_OPTION display_image=toggle; RELOAD"
# Toggle line number
keymap d COMMAND "SET_OPTION show_lnum=toggle"
# Yank current url
keymap yy       EXTERN     "echo -n %s | xsel -b"
# Yank url under cursor
keymap yf       EXTERN_LINK 'env printf %s "$0" | xsel -b'
#+end_src

** Cool scripts
I use these scripts to make w3m usable

1. FZF web search [4](example gif)
2. FZF bookmark search [5](example gif)
3. Torrent downloader [6](example gif)
4. Undo close tab [7](example gif)

You can grab all of these scripts [8]from my website.
You must place the scripts in cgi-bin-root in /usr/lib/w3m/cgi-bin/ and MUST have 755 permissions.
The scripts in the cgi-bin directory can be placed in ~/.w3m/cgi-bin/.
I'm pretty sure the reason for placing certain scripts in /usr/lib/w3m/cgi-bin has to do with those scripts sending http header information to W3M

You can setup keymaps to execute these scripts like this:

#+begin_src shell
# Fuzzy search search engines. Capital=New tab
keymap  ss      COMMAND       "SHELL ~/.w3m/cgi-bin/fzf_search.cgi ; GOTO /usr/lib/w3m/cgi-bin/goto_clipboard.cgi"
keymap  sS      COMMAND       "SHELL ~/.w3m/cgi-bin/fzf_search.cgi ; TAB_GOTO /usr/lib/w3m/cgi-bin/goto_clipboard.cgi"
# Fuzzy search bookmarks. Capital=New tab
keymap  sb      COMMAND       "SHELL ~/.w3m/cgi-bin/fzf_bookmarks.cgi ; GOTO /usr/lib/w3m/cgi-bin/goto_clipboard.cgi"
keymap  sB      COMMAND       "SHELL ~/.w3m/cgi-bin/fzf_bookmarks.cgi ; TAB_GOTO/usr/lib/w3m/cgi-bin/goto_clipboard.cgi"
# Close tab on ctrl-x and undo tab on ctrl-u
keymap  C-x      COMMAND     "EXTERN 'echo %s >> ~/.w3m/RestoreTab.txt' ; CLOSE_TAB"
keymap  C-u      TAB_GOTO    /usr/lib/w3m/cgi-bin/restore_tab.cgi
#+end_src

To get the magnet.py script to work, you need to create the file ~/.w3m/urimethodmap with this line added:

#+begin_src shell
magnet: file:/cgi-bin/magnet.py?%s
#+end_src

Opening a magnet link should now automatically send it to w3m.

** Tab operations
Here are my keybindings for tabbing.

#+begin_src shell
~/.w3m/keymap
keymap TAB NEXT_TAB
keymap M-TAB PREV_TAB
keymap C-t NEW_TAB
keymap T TAB_MENU
#+end_src

References

1. https://en.wikipedia.org/wiki/Common_Gateway_Interface
2. http://w3m.sourceforge.net/MANUAL#LocalCGI
3. https://github.com/felipesaa/A-vim-like-firefox-like-configuration-for-w3m/blob/master/keymap
4. file:///opt/webNew/content/pix/w3m-fzfsearch.gif
5. file:///opt/webNew/content/pix/w3m-fzfbookmark.gif
6. file:///opt/webNew/content/pix/w3m-magnet.gif
7. file:///opt/webNew/content/pix/w3m-undotab.gif
8. file:///opt/website/files/config/w3m/
