* Windows Changing Group Policy Rules from the Command Prompt
** Preface
Many of the group policy changes can be made from the registry.
The registry keys override the changes made in GPEDIT.MSC.
Microsoft has an Excel spreadsheet that outlines each group policy rule, it's description, path in GPEDIT.MSC, and the path in the registry.
You can download the [[https://www.microsoft.com/en-us/download/details.aspx?id=103668][Group Policy Settings Reference Spreadsheet for 21h2 here]].

Audit and Security policies have NO registry keys you can edit to modify them.
Changes to the audit and security policies have to be done in GPEDIT.msc
There's fortunatley a work around to this :)

Group Policy changes are stored in .pol database files in C:\Windows\System32\GroupPolicy.
Removing the folders contents will clear all changes to group policy.
Even though we can't edit the database, Microsoft has a separate utility we can download to make a group policy backup and import it from one computer to another.

This is better than the registry since the changes are reflected in group policy and auditing policies are able to be setup without to connet to each computer.

** LGPO.EXE
You can download the [[https://www.microsoft.com/en-us/download/details.aspx?id=55319][Microsoft Security Compliance Toolkit here]].
Download the LGPO zip file.
LGPO.EXE can be run portably.

** Usage
There are several different command line flags for this utility.
This probably isn't ideal, but I modify my local group policy on my computer and then make a backup.
The backup is then imported to other computers that I'm prepping.
Here are the commands to do that:

#+begin_src shell
# Backup your local group policy
lgpo.exe /b C:\windows\temp /n backup

LGPO.exe - Local Group Policy Object Utility
Version 3.0.2004.13001
Copyright (C) 2015-2020 Microsoft Corporation
Security Compliance Toolkit - https://www.microsoft.com/download/details.aspx?id=55319
Creating LGPO backup in "C:\windows\temp\{DA532EX7-5912-48B2-8867-FB172153DDSA}"

# Importing group policy to another computer
lgpo.exe /g "C:\windows\temp\{DA532EX7-5912-48B2-8867-FB172153DDSA}"
#+end_src 
