* Setting up an FTP over TLS
** Preface
Here's me documenting how to setup VSFTP on a home server.
I'm using a self-signed SSL certificate along with the /lftp/ client to connect to the server.

** Dependencies
/Very Secure FTP Daemon/ (server)
#+begin_src
apt install vsftpd
#+end_src

Install /lftp/ on the client machine to access FTPS

#+begin_src
apt install lftp
#+end_src

** Creating SSL certificate
SSL will provide encryption for file transfers and logins.

#+begin_src
mkdir -p /etc/vsftpd/ssl
openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/vsftpd/ssl/vsftpd.key -out /etc/vsftpd/ssl/vsftpd.pub -days 5000
#+end_src

** Configuration
I copied and tweaked the config from another website.
Truth be told, I don't know what every option does.

#+begin_src
# Add this to the new /etc/vsftpd.conf

listen=YES
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
chroot_local_user=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
pasv_enable=YES
pasv_min_port=10000
pasv_max_port=10100
allow_writeable_chroot=YES
rsa_cert_file=/etc/vsftpd/ssl/vsftpd.pem
rsa_private_key_file=/etc/vsftpd/ssl/vsftpd.pem
ssl_enable=YES
force_local_data_ssl=YES
force_local_logins_ssl=YES
ssl_tlsv1=YES
ssl_sslv2=NO
ssl_sslv3=NO
require_ssl_reuse=YES
ssl_ciphers=HIGH
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO
#+end_src

** Adding a new FTP user
This will be the only user that has FTP access.
#+begin_src
useradd -m ftpuser
passwd ftpuser
#+end_src

Append the user to the vsftpd.userlist

#+begin_src
echo "ftpuser" >> /etc/vsftpd.userlist
#+end_src

** Restarting/Enabling the service


#+begin_src
systemctl restart vsftpd
systemctl enable vsftpd
#+end_src

** Connecting using lftp 
We need to save the certificate on the client machine and then configure lftp to use it.
#+begin_src
echo | \
	openssl s_client -showcerts -connect IPADDRESS:21 -starttls ftp 2> /dev/null | \
	sed -n '/BEGIN CERTIFICATE/,/END CERTIFICATE/p' > ~/.config/lftp/mycert.crt

# Adding it to our local lftp config
cat << EOF >> ~/.config/lftp/rc
set ssl:ca-file "~/.config/lftp/mycert.crt"
set ssl:check-hostname no
EOF
#+end_src

Here's how I connect to it via the CLI

#+begin_src
lftp ftpuser@10.0.0.34
#+end_src

Alternatively you can use filezilla
