* # Playing K12 jnlp files (blackboard)

** ## Preface
This is only relevant if you attend K12 highschool online. K12 uses the
sucky blackboard system for live class connects. Blackboard uses Java
version 1.6 for it's class connects. We need to download
the correct version of java and run our jnlp file using javaws.

** ## Installing the right java version

Download Openjdk8(LTS) from [2]adoptopenjdk.net or from an archived
link [3]using the WayBackMachine

# Extracting the openjdk
tar -xzvf OpenJDK8*.tar.gz

* # Running our JNLP
Now that we have the correct version of java downloaded, we need
something to actually open our .jnlp file. We'll use icedtea for this.
The name of the package will vary depending on your system, so use your
package manager to search for it.

#+begin_src
# On Debian
$ apt install icedtea-netx

# I think it's "icedtea-webx" on Arch/Manajaro.
# I've also seen it named "icedtea-web"
#+end_src

After that, the next thing we have to do is run our class connect file.
We'll set the JAVA_HOME variable to the directory of the extracted openjdk enviroment.
"Javaws" (icedtea) looks at this variable to decide what java version it'll use to execute the file.

#+begin_src
$ export JAVA_HOME=/path/to/jdk8/
$ javaws class_connect.jnlp
#+end_src

# PROFIT!!!!!

[k12.png]

** ## Troubleshooting

If you're running a window manager you might see that the class connect runs fine, but the window is a blank screen.
The simplest fix I found was to use a DE such as lxde, mate, kde, etc.
I'm using mate in the photo above.

** ## References

 1. https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot
 2. https://web.archive.org/web/20200420070108/https://github-production-release-asset-2e65be.s3.amazonaws.com/140418865/c112f300-80b2-11ea-906e-c81beb978e10?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A/20200420/us-east-1/s3/aws4_request&X-Amz-Date=20200420T070108Z&X-Amz-Expires=300&X-Amz-Signature=b66e81f8991fab9d702306071214cafd69c189fc28e9c8aa86e48883bee2d87c&X-Amz-SignedHeaders=host&actor_id=0&repo_id=140418865&response-content-disposition=attachment; filename=OpenJDK8U-jdk_x64_linux_hotspot_8u252b09.tar.gz&response-content-type=application/octet-stream
